import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useStore } from '../store/useStore'
import { enrichLocation, computeOverlap } from '../lib/timezone'
import type { LocationWithTime, OverlapWindow } from '../lib/types'
import { flagEmoji } from '../lib/cities'

const HOURS = Array.from({ length: 24 }, (_, i) => i)

const statusColor = { available: '#22C55E', edge: '#F59E0B', sleeping: '#EF4444' }

function getHourStatus(loc: LocationWithTime, utcHour: number): 'available' | 'edge' | 'sleeping' {
  const now = new Date()
  now.setUTCHours(utcHour, 0, 0, 0)
  const localHour = parseInt(
    new Intl.DateTimeFormat('en-US', { timeZone: loc.timezone, hour: '2-digit', hour12: false }).format(now)
  )
  if (localHour >= loc.workStart && localHour < loc.workEnd) return 'available'
  if ((localHour >= loc.workStart - 2 && localHour < loc.workStart) || (localHour >= loc.workEnd && localHour < loc.workEnd + 3)) return 'edge'
  return 'sleeping'
}

function isOverlapHour(locations: LocationWithTime[], utcHour: number): boolean {
  return locations.every(loc => getHourStatus(loc, utcHour) === 'available')
}

function fmtUTCHour(h: number): string {
  const h24 = ((h % 24) + 24) % 24
  const label = `${String(h24).padStart(2, '0')}:00`
  return h >= 24 ? label + ' +1d' : label
}

function localTimeAtUTC(timezone: string, utcHour: number, hour12 = true): string {
  const d = new Date()
  d.setUTCHours(((utcHour % 24) + 24) % 24, 0, 0, 0)
  return new Intl.DateTimeFormat('en-US', {
    timeZone: timezone,
    hour: '2-digit',
    minute: '2-digit',
    hour12,
  }).format(d)
}

function buildSuggestedSlots(locs: LocationWithTime[], startUTC: number, durationHours: number, hour12 = true) {
  if (durationHours === 0) return []
  const rawSlots: number[] = []
  if (durationHours >= 1) rawSlots.push(startUTC)
  if (durationHours >= 3) rawSlots.push(startUTC + Math.floor(durationHours / 2))
  if (durationHours >= 2) rawSlots.push(startUTC + durationHours - 1)
  // deduplicate
  const slots = [...new Set(rawSlots)]
  return slots.map(utcH => ({
    utcHour: ((utcH % 24) + 24) % 24,
    label: fmtUTCHour(utcH),
    localTimes: locs.map(l => ({
      city: l.city,
      countryCode: l.countryCode,
      time: localTimeAtUTC(l.timezone, utcH, hour12),
    })),
  }))
}

function buildInviteText(locs: LocationWithTime[], overlap: OverlapWindow, hour12 = true): string {
  const slots = buildSuggestedSlots(locs, overlap.startUTC, overlap.durationHours, hour12)
  const best = slots[Math.floor(slots.length / 2)] ?? slots[0]
  if (!best) return ''
  const lines = [
    `Meeting Proposal — ${overlap.durationHours}h overlap window`,
    `Suggested: UTC ${best.label}`,
    '',
    ...best.localTimes.map(lt => `  ${lt.city}: ${lt.time}`),
    '',
    `Quality score: ${overlap.qualityScore}%`,
    `Generated by TimeOps`,
  ]
  return lines.join('\n')
}

// ─── Component ───────────────────────────────────────────────────────────────

export function OverlapView() {
  const navigate = useNavigate()
  const { locations, userTimezone, hour12 } = useStore()
  const [enriched, setEnriched] = useState<LocationWithTime[]>([])
  const [overlap, setOverlap] = useState<OverlapWindow | null>(null)
  const [copied, setCopied] = useState(false)
  const timelineRef = useRef<HTMLDivElement>(null)

  const currentUTCHour = new Date().getUTCHours()

  useEffect(() => {
    const run = () => {
      const e = locations.map(l => enrichLocation(l, userTimezone, hour12))
      setEnriched(e)
      setOverlap(computeOverlap(locations))
    }
    run()
    const t = setInterval(run, 10000)
    return () => clearInterval(t)
  }, [locations, userTimezone, hour12])

  // Auto-scroll timeline to current UTC hour
  useEffect(() => {
    if (!timelineRef.current) return
    const col = 29 // column width in px (28px + 1px gap)
    const labelCol = 88 // label column width
    const scrollTarget = labelCol + currentUTCHour * col - timelineRef.current.clientWidth / 2
    timelineRef.current.scrollLeft = Math.max(0, scrollTarget)
  }, [enriched, currentUTCHour])

  const copyInvite = async () => {
    if (!overlap) return
    const text = buildInviteText(enriched, overlap, hour12)
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch { /* no permission */ }
  }

  const overlapHoursSet = new Set(
    HOURS.filter(h => isOverlapHour(enriched, h))
  )

  const suggestedSlots = overlap
    ? buildSuggestedSlots(enriched, overlap.startUTC, overlap.durationHours, hour12)
    : []

  // Time until next overlap
  let hoursUntilOverlap: number | null = null
  if (overlap && overlap.durationHours > 0 && !overlapHoursSet.has(currentUTCHour)) {
    for (let i = 1; i <= 24; i++) {
      if (overlapHoursSet.has((currentUTCHour + i) % 24)) {
        hoursUntilOverlap = i
        break
      }
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100dvh', background: '#0F172A' }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '20px 20px 12px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button
            onClick={() => navigate('/')}
            style={{ background: '#1E293B', border: 'none', borderRadius: 10, width: 36, height: 36, color: '#94A3B8', fontSize: 18, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
          >‹</button>
          <div>
            <div style={{ fontSize: 16, fontWeight: 700, color: '#F8FAFC' }}>Overlap Intelligence</div>
            <div style={{ fontSize: 11, color: '#475569' }}>
              {enriched.length >= 2
                ? `${enriched.length} locations · UTC ${String(currentUTCHour).padStart(2, '0')}:${String(new Date().getUTCMinutes()).padStart(2, '0')} now`
                : 'Working hours across all zones'}
            </div>
          </div>
        </div>
        {overlap && overlap.durationHours > 0 && (
          <button
            onClick={copyInvite}
            style={{
              background: copied ? '#16532730' : '#1E293B',
              border: copied ? '1px solid #22C55E40' : '1px solid #334155',
              borderRadius: 10, padding: '8px 14px',
              color: copied ? '#22C55E' : '#94A3B8',
              fontSize: 12, fontWeight: 600, cursor: 'pointer',
            }}
          >
            {copied ? '✓ Copied' : '📋 Copy Invite'}
          </button>
        )}
      </div>

      <div style={{ flex: 1, overflowY: 'auto', padding: '0 16px 80px' }}>
        {enriched.length < 2 ? (
          <div style={{ textAlign: 'center', color: '#475569', padding: '60px 20px', fontSize: 14 }}>
            <div style={{ fontSize: 40, marginBottom: 12 }}>🌐</div>
            Add at least 2 locations to see overlap analysis.
          </div>
        ) : (
          <>
            {/* ── Status banner ── */}
            {overlapHoursSet.has(currentUTCHour) ? (
              <div style={{
                background: '#16532730', border: '1px solid #22C55E40',
                borderRadius: 12, padding: '10px 16px', marginBottom: 12,
                display: 'flex', alignItems: 'center', gap: 10,
              }}>
                <div style={{ width: 8, height: 8, borderRadius: '50%', background: '#22C55E', boxShadow: '0 0 8px #22C55E' }} />
                <span style={{ fontSize: 13, fontWeight: 700, color: '#22C55E' }}>Overlap active now — great time to connect!</span>
              </div>
            ) : hoursUntilOverlap !== null ? (
              <div style={{
                background: '#78350f20', border: '1px solid #F59E0B40',
                borderRadius: 12, padding: '10px 16px', marginBottom: 12,
                display: 'flex', alignItems: 'center', gap: 10,
              }}>
                <span style={{ fontSize: 16 }}>⏰</span>
                <span style={{ fontSize: 13, fontWeight: 700, color: '#F59E0B' }}>
                  Next overlap in ~{hoursUntilOverlap}h · UTC {fmtUTCHour((currentUTCHour + hoursUntilOverlap) % 24)}
                </span>
              </div>
            ) : null}

            {/* ── 24h Timeline Grid ── */}
            <div style={{
              background: '#1E293B',
              borderRadius: 16,
              padding: '16px 0 12px',
              marginBottom: 16,
              overflowX: 'auto',
            }} ref={timelineRef}>
              {/* Hour labels */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: `88px repeat(24, 28px)`,
                paddingLeft: 12,
                marginBottom: 6,
              }}>
                <div style={{ fontSize: 9, color: '#475569', fontWeight: 600, display: 'flex', alignItems: 'center' }}>UTC / LOCAL</div>
                {HOURS.map(h => (
                  <div key={h} style={{
                    fontSize: 9,
                    color: h === currentUTCHour ? '#60A5FA' : overlapHoursSet.has(h) ? 'var(--color-primary)' : '#475569',
                    textAlign: 'center',
                    fontWeight: h === currentUTCHour ? 700 : 400,
                  }}>
                    {h}
                  </div>
                ))}
              </div>

              {/* Per-location rows */}
              {enriched.map(loc => (
                <div key={loc.id} style={{ paddingLeft: 12, marginBottom: 4 }}>
                  {/* Location label row */}
                  <div style={{
                    display: 'grid',
                    gridTemplateColumns: `88px repeat(24, 28px)`,
                    alignItems: 'center',
                    marginBottom: 2,
                  }}>
                    <div style={{ fontSize: 10, color: '#94A3B8', display: 'flex', alignItems: 'center', gap: 4, paddingRight: 6 }}>
                      <span style={{ fontSize: 13 }}>{flagEmoji(loc.countryCode)}</span>
                      <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 54 }}>
                        {loc.city}
                      </span>
                    </div>
                    {HOURS.map(h => {
                      const s = getHourStatus(loc, h)
                      const isNow = h === currentUTCHour
                      const isOv = overlapHoursSet.has(h) && s === 'available'
                      return (
                        <div
                          key={h}
                          title={`UTC ${h}:00 → ${localTimeAtUTC(loc.timezone, h, hour12)} local (${s})`}
                          style={{
                            height: 22,
                            background: isOv ? 'color-mix(in srgb, var(--color-primary) 60%, #22C55E)' : statusColor[s],
                            opacity: s === 'sleeping' ? 0.2 : isOv ? 1 : 0.75,
                            borderRadius: 3,
                            margin: '0 1px',
                            outline: isNow ? '2px solid #60A5FA' : 'none',
                            outlineOffset: 1,
                            cursor: 'default',
                          }}
                        />
                      )
                    })}
                  </div>
                  {/* Local time label row (every 4 hours) */}
                  <div style={{
                    display: 'grid',
                    gridTemplateColumns: `88px repeat(24, 28px)`,
                    marginBottom: 2,
                  }}>
                    <div />
                    {HOURS.map(h => (
                      <div key={h} style={{
                        fontSize: 7,
                        color: '#334155',
                        textAlign: 'center',
                        overflow: 'hidden',
                      }}>
                        {h % 4 === 0 ? localTimeAtUTC(loc.timezone, h, hour12).replace(':00', '').replace(' AM', 'a').replace(' PM', 'p') : ''}
                      </div>
                    ))}
                  </div>
                </div>
              ))}

              {/* Overlap row */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: `88px repeat(24, 28px)`,
                paddingLeft: 12,
                marginTop: 6,
                paddingTop: 8,
                borderTop: '1px solid #334155',
                alignItems: 'center',
              }}>
                <div style={{ fontSize: 10, color: '#64748B', fontWeight: 700, letterSpacing: '0.04em' }}>OVERLAP</div>
                {HOURS.map(h => {
                  const isOv = overlapHoursSet.has(h)
                  const isNow = h === currentUTCHour
                  return (
                    <div key={h} style={{
                      height: 22,
                      background: isOv ? 'var(--color-primary)' : 'transparent',
                      borderRadius: 3,
                      margin: '0 1px',
                      boxShadow: isOv ? '0 0 6px color-mix(in srgb, var(--color-primary) 50%, transparent)' : 'none',
                      outline: isNow ? '2px solid #60A5FA' : 'none',
                      outlineOffset: 1,
                    }} />
                  )
                })}
              </div>
            </div>

            {/* ── Legend ── */}
            <div style={{ display: 'flex', gap: 16, marginBottom: 16, flexWrap: 'wrap' }}>
              {[
                { color: '#22C55E', label: 'Available' },
                { color: '#F59E0B', label: 'Edge Hours' },
                { color: '#EF4444', label: 'Sleeping' },
                { color: 'var(--color-primary)', label: 'Overlap' },
              ].map(({ color, label }) => (
                <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                  <div style={{ width: 12, height: 12, borderRadius: 3, background: color }} />
                  <span style={{ fontSize: 11, color: '#94A3B8' }}>{label}</span>
                </div>
              ))}
              <span style={{ fontSize: 11, color: '#334155', marginLeft: 'auto' }}>Local time labels shown below each row</span>
            </div>

            {/* ── Overlap Summary ── */}
            {overlap && overlap.durationHours > 0 ? (
              <>
                <div style={{
                  background: '#1E293B',
                  borderRadius: 16,
                  padding: '16px',
                  border: '1px solid #334155',
                  marginBottom: 14,
                }}>
                  <div style={{ fontSize: 11, color: '#64748B', marginBottom: 8, fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase' }}>Best Overlap Window</div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
                    <div>
                      <div style={{ fontSize: 22, fontWeight: 800, color: 'var(--color-primary)' }}>
                        {overlap.durationHours}h window
                      </div>
                      <div style={{ fontSize: 12, color: '#64748B', marginTop: 2 }}>
                        UTC {fmtUTCHour(overlap.startUTC)} – {fmtUTCHour(overlap.endUTC)}
                      </div>
                    </div>
                    <div style={{
                      background: 'color-mix(in srgb, var(--color-primary) 15%, #0F172A)',
                      borderRadius: 14,
                      padding: '10px 16px',
                      textAlign: 'center',
                      border: '1px solid color-mix(in srgb, var(--color-primary) 25%, transparent)',
                    }}>
                      <div style={{ fontSize: 20, fontWeight: 800, color: 'var(--color-primary)' }}>{overlap.qualityScore}%</div>
                      <div style={{ fontSize: 10, color: '#64748B' }}>Quality</div>
                    </div>
                  </div>

                  {/* Local times per location */}
                  {overlap.localTimes.map(lt => (
                    <div key={lt.locationId} style={{
                      display: 'flex', justifyContent: 'space-between',
                      padding: '8px 0',
                      borderTop: '1px solid #334155',
                    }}>
                      <span style={{ fontSize: 13, color: '#94A3B8' }}>{lt.city}</span>
                      <span style={{ fontSize: 13, fontWeight: 700, color: '#F8FAFC' }}>
                        {lt.start} – {lt.end}
                      </span>
                    </div>
                  ))}
                </div>

                {/* ── Suggested Meeting Slots ── */}
                {suggestedSlots.length > 0 && (
                  <div style={{ marginBottom: 14 }}>
                    <div style={{ fontSize: 11, color: '#64748B', marginBottom: 10, fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase' }}>
                      Suggested Meeting Times
                    </div>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                      {suggestedSlots.map((slot, i) => (
                        <div key={i} style={{
                          background: '#1E293B',
                          borderRadius: 14,
                          padding: '14px 16px',
                          border: i === Math.floor(suggestedSlots.length / 2)
                            ? '1px solid color-mix(in srgb, var(--color-primary) 40%, transparent)'
                            : '1px solid #334155',
                        }}>
                          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                              <span style={{ fontSize: 12, fontWeight: 700, color: 'var(--color-primary)' }}>UTC {slot.label}</span>
                              {i === Math.floor(suggestedSlots.length / 2) && (
                                <span style={{ fontSize: 10, background: 'color-mix(in srgb, var(--color-primary) 20%, transparent)', color: 'var(--color-primary)', padding: '2px 8px', borderRadius: 6, fontWeight: 600 }}>
                                  Recommended
                                </span>
                              )}
                            </div>
                            {i === 0 && <span style={{ fontSize: 10, color: '#475569' }}>Start</span>}
                            {i === suggestedSlots.length - 1 && i !== 0 && <span style={{ fontSize: 10, color: '#475569' }}>Last slot</span>}
                          </div>
                          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                            {slot.localTimes.map(lt => (
                              <div key={lt.city} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <span style={{ fontSize: 12, color: '#64748B', display: 'flex', alignItems: 'center', gap: 6 }}>
                                  <span style={{ fontSize: 14 }}>{flagEmoji(lt.countryCode)}</span>
                                  {lt.city}
                                </span>
                                <span style={{ fontSize: 13, fontWeight: 700, color: '#F8FAFC' }}>{lt.time}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </>
            ) : (
              <div style={{
                background: '#1E293B',
                borderRadius: 16,
                padding: '28px 20px',
                textAlign: 'center',
                border: '1px solid #7f1d1d40',
              }}>
                <div style={{ fontSize: 32, marginBottom: 10 }}>⚠️</div>
                <div style={{ fontSize: 15, fontWeight: 700, color: '#EF4444', marginBottom: 6 }}>No working-hour overlap</div>
                <div style={{ fontSize: 12, color: '#64748B', lineHeight: 1.6 }}>
                  Your locations have no shared working hours today.<br />
                  Consider adjusting work hours or scheduling across days.
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}
